# Generated by Django 3.0.8 on 2020-10-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=120)),
                ('image', models.URLField(null=True)),
                ('category', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=25, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_bid_listing', to='auctions.Bid')),
            ],
        ),
    ]
